# Generated by Django 2.2 on 2019-04-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('clave_mayor', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Cuentas contables',
                'db_table': 'cuenta_contable',
                'ordering': ['num_cuenta'],
                'managed': True,
            },
        ),
    ]
