# Generated by Django 2.2 on 2019-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0003_periodocorte_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodocorte',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
