# Generated by Django 2.2 on 2019-05-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0004_auto_20190429_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcumuladoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominio', models.CharField(blank=True, max_length=45, null=True)),
                ('cuenta_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('mes', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('depositos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('retiros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Acumulados mensuales',
                'db_table': 'sadiochouno_acumulado_mes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Condomino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(blank=True, max_length=15, null=True)),
                ('propietario', models.CharField(blank=True, max_length=60, null=True)),
                ('poseedor', models.CharField(blank=True, max_length=60, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_escrituracion', models.DateField(blank=True, null=True)),
                ('referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indiviso', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('adeudo_inicial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('fecha_corte_saldo', models.DateField(blank=True, null=True)),
                ('cargos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('pagos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_condomino_condominio_id', to='Catalogos.Condominio')),
            ],
            options={
                'db_table': 'sadiochouno_condomino',
                'ordering': ['depto'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=20)),
                ('clabe', models.CharField(max_length=18)),
                ('apoderado', models.CharField(max_length=60)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Saldo inicial')),
                ('fecha_saldo', models.DateField(blank=True, null=True)),
                ('situacion', models.IntegerField(blank=True, null=True)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_banco_cta', to='Catalogos.Banco')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_cta_condominio', to='Catalogos.Condominio')),
            ],
            options={
                'verbose_name_plural': 'Cuentas bancarias',
                'db_table': 'sadiochouno_cuenta_banco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha_expedicion', models.DateField()),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('notas', models.CharField(blank=True, max_length=45, null=True)),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_recibo_situacion_id', to='Catalogos.Situacion')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_recibo_tipodoc_id', to='Catalogos.TipoDocumento')),
            ],
            options={
                'db_table': 'sadiochouno_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'sadiochouno_estacionamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('retiro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('condomino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_mov_condomino_id', to='SadiCarnot81.Condomino')),
                ('cuenta_banco', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_mov_cuenta_id', to='SadiCarnot81.CuentaBanco')),
                ('documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_mov_documento_id', to='SadiCarnot81.Documento')),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_mov_tipo_mov_id', to='Catalogos.TipoMovimiento')),
            ],
            options={
                'db_table': 'sadiochouno_movimiento',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cuenta_contable', models.ForeignKey(limit_choices_to=models.Q(('clave_mayor', '41'), ('clave_mayor', '51'), ('num_cuenta', '2318'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='sadiochouno_cta_detalle', to='Catalogos.CuentaContable', verbose_name='Cuenta Contable Ingreso/Egreso')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadiochouno_mov_detalle', to='SadiCarnot81.Movimiento', verbose_name='Movto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadiochouno_prov_detalle', to='Catalogos.Proveedore', verbose_name='Proveedor/Depto')),
            ],
            options={
                'db_table': 'sadiochouno_detalle_movimiento',
                'ordering': ['movimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuotasCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('mes_inicial', models.DateField(blank=True, null=True)),
                ('mes_final', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('condomino', models.ManyToManyField(related_name='sadiochouno_cuotas_condomino_id', to='SadiCarnot81.Condomino')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadiochouno_cuota_cuenta', to='Catalogos.CuentaContable', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name_plural': 'Cuotas del condominio',
                'db_table': 'sadiochouno_cuotas',
                'ordering': ['mes_inicial'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='condomino',
            name='estacionamiento',
            field=models.ManyToManyField(related_name='sadiochouno_condomino_estac_id', to='SadiCarnot81.Estacionamiento'),
        ),
    ]
