# Generated by Django 2.2 on 2019-05-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot81', '0002_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadiochouno_asiento_cuenta', to='Catalogos.CuentaContable', verbose_name='Cuenta Contable'),
        ),
    ]
