# Generated by Django 2.2 on 2019-05-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot81', '0003_auto_20190515_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='a_favor',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cuenta_contable',
        ),
    ]
