# Generated by Django 2.2 on 2019-05-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot81', '0004_auto_20190515_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='tipo_movimiento',
        ),
    ]
