# Generated by Django 2.2 on 2019-04-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0002_cuentacontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condomino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(blank=True, max_length=15, null=True)),
                ('propietario', models.CharField(blank=True, max_length=60, null=True)),
                ('poseedor', models.CharField(blank=True, max_length=60, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_escrituracion', models.DateField(blank=True, null=True)),
                ('referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_condomino_condominio_id', to='Catalogos.Condominio')),
            ],
            options={
                'db_table': 'sadi_condomino',
                'ordering': ['depto'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=20)),
                ('clabe', models.CharField(max_length=18)),
                ('apoderado', models.CharField(max_length=60)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_saldo', models.DateField(blank=True, null=True)),
                ('situacion', models.IntegerField(blank=True, null=True)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_banco_cuenta', to='Catalogos.Banco')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_cuenta_condominio', to='Catalogos.Condominio')),
            ],
            options={
                'verbose_name_plural': 'Cuentas bancarias',
                'db_table': 'sadi_cuenta_banco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha_expedicion', models.DateField()),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('notas', models.CharField(blank=True, max_length=45, null=True)),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_recibo_situacion_id', to='Catalogos.Situacion')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_recibo_tipodoc_id', to='Catalogos.TipoDocumento')),
            ],
            options={
                'db_table': 'sadi_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'sadi_estacionamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('retiro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=9, null=True)),
                ('condomino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_condomino_id', to='SadiCarnot10.Condomino')),
                ('cuenta_banco', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_cuenta_id', to='SadiCarnot10.CuentaBanco')),
                ('documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_documento_id', to='SadiCarnot10.Documento')),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_tipo_movimiento_id', to='Catalogos.TipoMovimiento')),
            ],
            options={
                'db_table': 'sadi_movimiento',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cuenta_contable', models.ForeignKey(limit_choices_to=models.Q(('clave_mayor', '41'), ('clave_mayor', '51'), ('num_cuenta', '2318'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='sadi_cta_detalle', to='Catalogos.CuentaContable', verbose_name='Cuenta Contable Ingreso/Egreso')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadi_mov_detalle', to='SadiCarnot10.Movimiento', verbose_name='Movto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadi_prov_detalle', to='Catalogos.Proveedore', verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'sadi_detalle_movimiento',
                'ordering': ['movimiento'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='condomino',
            name='estacionamiento',
            field=models.ManyToManyField(related_name='sadi_condomino_estacionamiento_id', to='SadiCarnot10.Estacionamiento'),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('a_favor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_auxiliar_proveedor_id', to='Catalogos.Proveedore')),
                ('condomino', models.ForeignKey(default=67, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_auxiliar_condomino_id', to='SadiCarnot10.Condomino')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadi_asiento_cuenta', to='Catalogos.CuentaContable', verbose_name='Cuenta Contable')),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_auxiliar_tipo_movimiento_id', to='Catalogos.TipoMovimiento')),
            ],
            options={
                'db_table': 'sadi_asiento',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
    ]
