# Generated by Django 2.2 on 2019-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcumuladoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominio', models.CharField(blank=True, max_length=45, null=True)),
                ('cuenta_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('mes', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('depositos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('retiros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Acumulados mensuales',
                'db_table': 'sadi_acumulado_mes',
                'managed': True,
            },
        ),
    ]
