# Generated by Django 2.2 on 2019-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot10', '0002_acumuladomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo inicial'),
        ),
    ]
