# Generated by Django 2.2 on 2019-05-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0004_auto_20190429_1144'),
        ('SadiCarnot10', '0003_auto_20190429_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'managed': True, 'ordering': ['fecha'], 'verbose_name_plural': 'Movimientos bancarios'},
        ),
        migrations.CreateModel(
            name='CuotasCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('mes_inicial', models.DateField(blank=True, null=True)),
                ('mes_final', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadi_cuota_cuenta', to='Catalogos.CuentaContable', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name_plural': 'Cuotas del condominio',
                'db_table': 'sadi_cuotas',
                'managed': True,
            },
        ),
    ]
