# Generated by Django 2.2 on 2019-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot10', '0004_auto_20190430_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotascondominio',
            options={'managed': True, 'ordering': ['mes_inicial'], 'verbose_name_plural': 'Cuotas del condominio'},
        ),
        migrations.AddField(
            model_name='condomino',
            name='adeudo_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='condomino',
            name='fecha_corte_saldo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotascondominio',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
