# Generated by Django 2.2 on 2019-05-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot10', '0006_auto_20190502_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomino',
            name='pagos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
