# Generated by Django 2.2 on 2019-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot10', '0007_condomino_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotascondominio',
            name='condomino',
            field=models.ManyToManyField(related_name='sadi_cuotas_condomino_id', to='SadiCarnot10.Condomino'),
        ),
    ]
