# Generated by Django 2.2 on 2019-05-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0004_auto_20190429_1144'),
        ('SadiCarnot10', '0009_auto_20190509_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asiento',
            new_name='Registro',
        ),
    ]
