# Generated by Django 2.2 on 2019-05-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SadiCarnot10', '0010_auto_20190510_2126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro',
            table='sadi_registro',
        ),
    ]
