# Generated by Django 2.2 on 2019-04-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0004_auto_20190429_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catalogos.Condominio')),
            ],
            options={
                'db_table': 'periodo_procesos',
                'managed': True,
            },
        ),
    ]
