# Generated by Django 2.2 on 2019-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoproceso',
            options={'managed': True, 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterField(
            model_name='periodoproceso',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Saldo final'),
        ),
    ]
