# Generated by Django 2.2 on 2019-05-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0002_auto_20190429_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoproceso',
            options={'managed': True, 'verbose_name_plural': 'Acumulados'},
        ),
    ]
